deployments:
  MyApp:
    ready_wait: 20  
    dockerimage: ubuntu:trusty
    build_steps:
      - apt-get update && apt-get -y install python-pip
      - pip install flask
    launch_steps:
      - cd /code
      - python server.py
    port_forwarding: 80:3000
    run_options: -v "~/code:/code"
